--- #YAML:1.0
name: Maypole-Plugin-QuickTable
version: 0.32
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: HTML::QuickTable goodness for Maypole
license: perl
requires:
  HTML::QuickTable: 0
  Maypole::Config: 0
  NEXT: 0
  Test::More: 0
provides:
  Maypole::Plugin::QuickTable:
    file: lib/Maypole/Plugin/QuickTable.pm
    version: 0.32
generated_by: Module::Build version 0.2609
